/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as CareRouteRouteImport } from './routes/care/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppCalendarRouteImport } from './routes/app/calendar'
import { Route as AppInboxRouteImport } from './routes/app/inbox'
import { Route as AppJourneyRouteImport } from './routes/app/journey'
import { Route as AppOnboardRouteImport } from './routes/app/onboard'
import { Route as AppOrdersRouteImport } from './routes/app/orders'
import { Route as AppPatientsRouteImport } from './routes/app/patients'
import { Route as CareIndexRouteImport } from './routes/care/index'
import { Route as CareBookRouteImport } from './routes/care/book'
import { Route as CareOnboardRouteImport } from './routes/care/onboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppPatientsIdRouteImport } from './routes/app/patients_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRouteRoute = CareRouteRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppJourneyRoute = AppJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardRoute = AppOnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRouteRoute,
} as any)
const CareIndexRoute = CareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareRouteRoute,
} as any)
const CareBookRoute = CareBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => CareRouteRoute,
} as any)
const CareOnboardRoute = CareOnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => CareRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPatientsIdRoute = AppPatientsIdRouteImport.update({
  id: '/patients_/$id',
  path: '/patients/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/care': typeof CareRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/journey': typeof AppJourneyRoute
  '/app/onboard': typeof AppOnboardRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/patients': typeof AppPatientsRoute
  '/care/book': typeof CareBookRoute
  '/care/onboard': typeof CareOnboardRoute
  '/app/': typeof AppIndexRoute
  '/care/': typeof CareIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/patients/$id': typeof AppPatientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/journey': typeof AppJourneyRoute
  '/app/onboard': typeof AppOnboardRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/patients': typeof AppPatientsRoute
  '/care/book': typeof CareBookRoute
  '/care/onboard': typeof CareOnboardRoute
  '/app': typeof AppIndexRoute
  '/care': typeof CareIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/patients/$id': typeof AppPatientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/care': typeof CareRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/journey': typeof AppJourneyRoute
  '/app/onboard': typeof AppOnboardRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/patients': typeof AppPatientsRoute
  '/care/book': typeof CareBookRoute
  '/care/onboard': typeof CareOnboardRoute
  '/app/': typeof AppIndexRoute
  '/care/': typeof CareIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/patients_/$id': typeof AppPatientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/care'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/calendar'
    | '/app/inbox'
    | '/app/journey'
    | '/app/onboard'
    | '/app/orders'
    | '/app/patients'
    | '/care/book'
    | '/care/onboard'
    | '/app/'
    | '/care/'
    | '/api/auth/$'
    | '/app/patients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/calendar'
    | '/app/inbox'
    | '/app/journey'
    | '/app/onboard'
    | '/app/orders'
    | '/app/patients'
    | '/care/book'
    | '/care/onboard'
    | '/app'
    | '/care'
    | '/api/auth/$'
    | '/app/patients/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/care'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/calendar'
    | '/app/inbox'
    | '/app/journey'
    | '/app/onboard'
    | '/app/orders'
    | '/app/patients'
    | '/care/book'
    | '/care/onboard'
    | '/app/'
    | '/care/'
    | '/api/auth/$'
    | '/app/patients_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  CareRouteRoute: typeof CareRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/journey': {
      id: '/app/journey'
      path: '/journey'
      fullPath: '/app/journey'
      preLoaderRoute: typeof AppJourneyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/onboard': {
      id: '/app/onboard'
      path: '/onboard'
      fullPath: '/app/onboard'
      preLoaderRoute: typeof AppOnboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/patients': {
      id: '/app/patients'
      path: '/patients'
      fullPath: '/app/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/care/': {
      id: '/care/'
      path: '/'
      fullPath: '/care/'
      preLoaderRoute: typeof CareIndexRouteImport
      parentRoute: typeof CareRouteRoute
    }
    '/care/book': {
      id: '/care/book'
      path: '/book'
      fullPath: '/care/book'
      preLoaderRoute: typeof CareBookRouteImport
      parentRoute: typeof CareRouteRoute
    }
    '/care/onboard': {
      id: '/care/onboard'
      path: '/onboard'
      fullPath: '/care/onboard'
      preLoaderRoute: typeof CareOnboardRouteImport
      parentRoute: typeof CareRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/patients_/$id': {
      id: '/app/patients_/$id'
      path: '/patients/$id'
      fullPath: '/app/patients/$id'
      preLoaderRoute: typeof AppPatientsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppInboxRoute: typeof AppInboxRoute
  AppJourneyRoute: typeof AppJourneyRoute
  AppOnboardRoute: typeof AppOnboardRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPatientsIdRoute: typeof AppPatientsIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppInboxRoute: AppInboxRoute,
  AppJourneyRoute: AppJourneyRoute,
  AppOnboardRoute: AppOnboardRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppIndexRoute: AppIndexRoute,
  AppPatientsIdRoute: AppPatientsIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface CareRouteRouteChildren {
  CareBookRoute: typeof CareBookRoute
  CareOnboardRoute: typeof CareOnboardRoute
  CareIndexRoute: typeof CareIndexRoute
}

const CareRouteRouteChildren: CareRouteRouteChildren = {
  CareBookRoute: CareBookRoute,
  CareOnboardRoute: CareOnboardRoute,
  CareIndexRoute: CareIndexRoute,
}

const CareRouteRouteWithChildren = CareRouteRoute._addFileChildren(
  CareRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  CareRouteRoute: CareRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
